<?php
return [
    'pl' => [
        'lang' => 'pl',
        'notification_title' => 'Potwierdzenie rejestracji',
        'greeting' => 'Witaj, {IMIĘ I NAZWISKO (PRACOWNIKA):1}!',
        'confirmation_text' => 'Dziękujmy za wypełnienie formularza. Spersonalizowany identyfikator będzie czekał na odbiór w Biurze Wystawców na targach <b>[trade_fair_name]</b> odbywających się w dniach <b>[trade_fair_date]</b> w Ptak Warsaw Expo.',
        'regards' => 'Pozdrawiamy, Zespół [trade_fair_name]',
        'auto_message' => 'Wiadomość wygenerowana automatycznie, prosimy na nią nie odpowiadać.',
        'copyright_text' => 'Wszystkie prawa zastrzeżone',
        'privacy_notice' => 'Administratorem Pani/Pana danych osobowych jest spółka PTAK WARSAW EXPO sp. z o.o. z siedzibą w Nadarzynie (kod pocztowy: 05-830), przy Al. Katowickiej 62, wpisaną do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS 0000671001, NIP 532544579. Dane osobowe będą przetwarzane zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (RODO), na podstawie art. 6 ust. 1 lit. a lub b ww. Rozporządzenia w celach wskazanych w treści ww. zgód. Dane będą przetwarzane do czasu wycofania zgody i będą podlegały okresowemu przeglądowi co 2 lata. Pani/a dane osobowe mogą być przekazane osobom trzecim, które przetwarzają dane osobowe w imieniu PTAK WARSAW EXPO sp. z o.o. na podstawie umów powierzenia tj. usługi IT, podmioty świadczące usługi marketingowe, podmioty przetwarzające dane w celu dochodzenia roszczeń i windykacji lub innych. Ma Pan/i możliwość dostępu do swoich danych, w celu ich sprostowania i usunięcia, przeniesienia danych oraz żądania ograniczenia ich przetwarzania ze względu na swoją szczególną sytuację, wniesienia sprzeciwu oraz wycofania udzielonej zgody w każdym momencie, przy czym, cofnięcie uprzednio wyrażonej zgody nie wpłynie na legalność przetwarzania przed jej wycofaniem, a także wniesienia skargi do organu nadzorczego - Prezesa Urzędu Ochrony Danych Osobowych. Dane nie będą przekazywane do państw trzecich oraz nie podlegają profilowaniu tj. automatycznemu podejmowaniu decyzji. Kontakt z administratorem możliwy jest pod adresem e-mail: rodo@warsawexpo.eu.',
    ],
    'en' => [
        'lang' => 'en',
        'notification_title' => 'Registration Confirmation',
        'greeting' => 'Hello, {IMIĘ I NAZWISKO (PRACOWNIKA):1},',
        'confirmation_text' => 'Thank you for filling out the form. Your personalized badge will be waiting to be picked up at the Exhibitors\' Office at <b>[trade_fair_name_eng]</b> taking place on <b>[trade_fair_date_eng]</b> at Ptak Warsaw Expo.',
        'regards' => 'Best Regards, [trade_fair_name] Team',
        'auto_message' => 'Automatically generated message, please do not reply to it.',
        'copyright_text' => 'All rights reserved',
        'privacy_notice' => 'The administrator of your personal data is PTAK WARSAW EXPO sp.z o.o. with its registered office in Nadarzyn (postal code: 05-830), at Al. Katowicka 62, entered into the Register of Entrepreneurs of the National Court Register under the number KRS 0000671001, NIP 532544579. Personal data will be processed in accordance with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons in connection with processing of personal data and on the free movement of such data and repealing Directive 95/46 / EC (GDPR), pursuant to art. 6 clause 1 lit. a or b above Regulations for the purposes indicated in the content of the above approvals. The data will be processed until the consent is withdrawn and will be subject to periodic review every two years. Your personal data may be transferred to third parties who process personal data on behalf of PTAK WARSAW EXPO sp.z o.o. based on entrustment agreements, i.e. IT services, entities providing marketing services, entities processing data for the purpose of pursuing claims and recovery or other. You have the option of accessing your data, to rectify and delete them, transfer data and request to limit their processing due to your special situation, raise an objection and withdraw your consent at any time, however, withdrawing your consent will not affect on the legality of processing before its withdrawal, as well as lodging a complaint to the supervisory body - the President of the Office for Personal Data Protection. The data will not be transferred to third countries and are not subject to profiling, i.e. automatic decision making. Contact with the administrator is possible at the following e-mail address: rodo@warsawexpo.eu.',
    ],
];
