<?php

if (!defined('ABSPATH')) {
    exit;
}

return [
    'pl' => [
        'rodo_text' => 'Administratorem Pani/Pana danych osobowych jest spółka PTAK WARSAW EXPO sp. z o.o. z siedzibą w Nadarzynie (kod pocztowy: 05-830), przy Al. Katowickiej 62, wpisaną do rejestru przedsiębiorców Krajowego Rejestru Sądowego pod numerem KRS 0000671001, NIP 532544579. Dane osobowe będą przetwarzane zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (RODO), na podstawie art. 6 ust. 1 lit. a lub b ww. Rozporządzenia w celach wskazanych w treści ww. zgód. Dane będą przetwarzane do czasu wycofania zgody i będą podlegały okresowemu przeglądowi co 2 lata. Pani/a dane osobowe mogą być przekazane osobom trzecim, które przetwarzają dane osobowe w imieniu PTAK WARSAW EXPO sp. z o.o. na podstawie umów powierzenia tj. usługi IT, podmioty świadczące usługi marketingowe, podmioty przetwarzające dane w celu dochodzenia roszczeń i windykacji lub innych. Ma Pan/i możliwość dostępu do swoich danych, w celu ich sprostowania i usunięcia, przeniesienia danych oraz żądania ograniczenia ich przetwarzania ze względu na swoją szczególną sytuację, wniesienia sprzeciwu oraz wycofania udzielonej zgody w każdym momencie, przy czym, cofnięcie uprzednio wyrażonej zgody nie wpłynie na legalność przetwarzania przed jej wycofaniem, a także wniesienia skargi do organu nadzorczego - Prezesa Urzędu Ochrony Danych Osobowych. Dane nie będą przekazywane do państw trzecich oraz nie podlegają profilowaniu tj. automatycznemu podejmowaniu decyzji. Kontakt z administratorem możliwy jest pod adresem e-mail:',
    ],
    'en' => [
        'rodo_text' => 'The administrator of your personal data is PTAK WARSAW EXPO sp. z o.o. with its registered office in Nadarzyn (postal code: 05-830), at Al. Katowicka 62, entered in the register of entrepreneurs of the National Court Register under KRS number 0000671001, NIP 532544579. Personal data will be processed in accordance with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (GDPR), on the basis of Article 6(1)(a) or (b) of the above regulation, for the purposes set out in the relevant consents. Data will be processed until the consent is withdrawn and will be reviewed periodically every 2 years. Your personal data may be shared with third parties who process personal data on behalf of PTAK WARSAW EXPO sp. z o.o. under data processing agreements, including IT service providers, marketing service providers, entities processing data for debt collection and claims, or others. You have the right to access your data, rectify and delete it, transfer it, request restriction of processing due to your specific situation, object to processing, and withdraw your consent at any time. Withdrawal of previously given consent does not affect the lawfulness of processing carried out before withdrawal. You also have the right to lodge a complaint with the competent supervisory authority. Your data will not be transferred to third countries and will not be subject to profiling or automated decision-making. You can contact the administrator at the e-mail address:',
    ],
    'cs' => [
        'rodo_text' => 'Správcem vašich osobních údajů je společnost PTAK WARSAW EXPO sp. z o.o. se sídlem v Nadarzyně (PSČ: 05-830), Al. Katowicka 62, zapsaná v rejstříku podnikatelů Národního soudního rejstříku pod číslem KRS 0000671001, NIP 532544579. Osobní údaje budou zpracovávány v souladu s nařízením Evropského parlamentu a Rady (EU) 2016/679 ze dne 27. dubna 2016 o ochraně fyzických osob v souvislosti se zpracováním osobních údajů a o volném pohybu těchto údajů a o zrušení směrnice 95/46/ES (GDPR), na základě čl. 6 odst. 1 písm. a) nebo b) uvedeného nařízení pro účely uvedené v obsahu udělených souhlasů. Údaje budou zpracovávány do odvolání souhlasu a budou pravidelně revidovány každé 2 roky. Vaše osobní údaje mohou být předány třetím stranám, které zpracovávají osobní údaje jménem společnosti PTAK WARSAW EXPO sp. z o.o. na základě smluv o zpracování dat, včetně poskytovatelů IT služeb, marketingových služeb, subjektů zpracovávajících data pro vymáhání pohledávek a jiných. Máte právo přístupu ke svým údajům, opravy a výmazu, přenosu, omezení zpracování z důvodu Vaší konkrétní situace, vznesení námitky a odvolání souhlasu kdykoliv. Odvolání souhlasu neovlivní zákonnost zpracování provedeného před tímto odvoláním. Máte také právo podat stížnost příslušnému dozorovému orgánu. Vaše údaje nebudou přeneseny do třetích zemí a nebudou předmětem profilování ani automatizovaného rozhodování. Kontakt s administrátorem je možný na e-mailové adrese:',
    ],
    'de' => [
        'rodo_text' => 'Verantwortlicher für Ihre personenbezogenen Daten ist PTAK WARSAW EXPO sp. z o.o. mit Sitz in Nadarzyn (Postleitzahl: 05-830), Al. Katowicka 62, eingetragen im Unternehmerregister des Landesgerichtsregisters unter der Nummer KRS 0000671001, NIP 532544579. Die personenbezogenen Daten werden gemäß der Verordnung (EU) 2016/679 des Europäischen Parlaments und des Rates vom 27. April 2016 zum Schutz natürlicher Personen bei der Verarbeitung personenbezogener Daten, zum freien Datenverkehr und zur Aufhebung der Richtlinie 95/46/EG (DSGVO) verarbeitet, auf Grundlage von Art. 6 Abs. 1 Buchst. a oder b der genannten Verordnung für die in den entsprechenden Einwilligungen genannten Zwecke. Die Daten werden bis zum Widerruf der Einwilligung verarbeitet und periodisch alle 2 Jahre überprüft. Ihre personenbezogenen Daten können Dritten übermittelt werden, die im Auftrag von PTAK WARSAW EXPO sp. z o.o. personenbezogene Daten verarbeiten, darunter IT-Dienstleister, Marketingdienstleister, Unternehmen zur Geltendmachung von Ansprüchen und Inkasso oder andere. Sie haben das Recht auf Zugang zu Ihren Daten, deren Berichtigung und Löschung, Datenübertragbarkeit, Einschränkung der Verarbeitung aus Ihrer besonderen Situation heraus, Widerspruch und jederzeitigen Widerruf Ihrer Einwilligung. Ein Widerruf hat keine Auswirkung auf die Rechtmäßigkeit der vor dem Widerruf erfolgten Verarbeitung. Sie haben zudem das Recht, Beschwerde bei der zuständigen Aufsichtsbehörde einzulegen. Ihre Daten werden nicht in Drittländer übertragen und unterliegen weder einem Profiling noch automatisierten Entscheidungen. Kontakt mit dem Verantwortlichen ist per E-Mail möglich:',
    ],
    'et' => [
        'rodo_text' => 'Teie isikuandmete vastutav töötleja on PTAK WARSAW EXPO sp. z o.o., registrijärgse asukohaga Nadarzynis (postiindeks 05-830), Al. Katowicka 62, registreeritud riikliku kohturegistri ettevõtjate registris numbri KRS 0000671001 all, NIP 532544579. Isikuandmeid töödeldakse kooskõlas Euroopa Parlamendi ja nõukogu 27. aprilli 2016. aasta määrusega (EL) 2016/679, mis käsitleb füüsiliste isikute kaitset isikuandmete töötlemisel ja selliste andmete vaba liikumist, ning millega tunnistatakse kehtetuks direktiiv 95/46/EÜ (GDPR). Andmete töötlemine toimub määruse artikli 6 lõike 1 punkti a või b alusel ja vastavalt andmetöötluse nõusolekule. Andmeid töödeldakse kuni nõusoleku tagasivõtmiseni ja neid kontrollitakse iga 2 aasta tagant. Teie isikuandmeid võib edastada kolmandatele osapooltele, kes töötlevad andmeid PTAK WARSAW EXPO sp. z o.o. nimel andmetöötluslepingute alusel, sealhulgas IT-teenusepakkujad, turundusettevõtted ja muud osapooled. Teil on õigus tutvuda oma andmetega, neid parandada ja kustutada, anda andmete ülekanne, piirata andmete töötlemist, esitada vastuväiteid ja igal ajal nõusoleku tagasi võtta. Tagasivõtmine ei mõjuta varasemalt toimunud töötlemise seaduslikkust. Teil on samuti õigus esitada kaebus vastavale järelevalveorganile. Andmeid ei edastata kolmandatesse riikidesse ning neid ei kasutata profiliseerimiseks ega automatiseeritud otsuste tegemiseks. Vastutava töötlejaga saab ühendust võtta e-posti aadressil:',
    ],
    'it' => [
        'rodo_text' => 'Il titolare del trattamento dei dati personali è PTAK WARSAW EXPO sp. z o.o. con sede legale a Nadarzyn (codice postale: 05-830), Al. Katowicka 62, iscritta nel registro degli imprenditori del Registro Nazionale Giudiziario con il numero KRS 0000671001, NIP 532544579. I dati personali saranno trattati conformemente al Regolamento (UE) 2016/679 del Parlamento europeo e del Consiglio del 27 aprile 2016 relativo alla protezione delle persone fisiche con riguardo al trattamento dei dati personali e alla libera circolazione di tali dati, che abroga la direttiva 95/46/CE (GDPR), sulla base dell’art. 6, comma 1, lettera a) o b) del suddetto Regolamento, per le finalità indicate nei relativi consensi. I dati saranno trattati fino alla revoca del consenso e saranno soggetti a verifica periodica ogni 2 anni. I vostri dati personali possono essere comunicati a terzi che trattano i dati personali per conto di PTAK WARSAW EXPO sp. z o.o. in base a contratti di trattamento dei dati, inclusi fornitori di servizi IT, fornitori di servizi di marketing, soggetti che trattano dati per esercitare pretese e recupero crediti o altri. Hai il diritto di accedere ai tuoi dati, correggerli e cancellarli, trasferirli, richiedere la limitazione del trattamento in base alla tua situazione specifica, opporsi al trattamento e revocare il consenso in qualsiasi momento. La revoca del consenso non incide sulla liceità del trattamento effettuato prima della revoca. Hai inoltre il diritto di presentare reclamo all’autorità di controllo competente. I tuoi dati non verranno trasferiti a paesi terzi e non saranno soggetti a profilazione o decisioni automatizzate. Il contatto con il titolare del trattamento è possibile all’indirizzo e-mail:',
    ],
    'lt' => [
        'rodo_text' => 'Jūsų asmens duomenų valdytojas yra PTAK WARSAW EXPO sp. z o.o., kurios registruota buveinė yra Nadarzyn (pašto kodas 05-830), Al. Katowicka 62, įregistruota Nacionalinio teismų registro verslininkų registre numeriu KRS 0000671001, NIP 532544579. Asmens duomenys bus tvarkomi vadovaujantis Europos Parlamento ir Tarybos reglamentu (ES) 2016/679 dėl fizinių asmenų apsaugos tvarkant asmens duomenis bei laisvo tokių duomenų judėjimo ir Direktyvos 95/46/EB panaikinimo (BDAR). Asmens duomenų apdorojimas atliekamas pagal Reglamento 6 straipsnio 1 dalies a arba b punktą, atsižvelgiant į atitinkamų sutikimų turinį. Duomenys bus tvarkomi iki sutikimo atšaukimo ir periodiškai peržiūrimi kas 2 metus. Jūsų asmens duomenys gali būti perduodami trečiosioms šalims, kurios tvarko asmens duomenis PTAK WARSAW EXPO sp. z o.o. vardu pagal duomenų tvarkymo sutartis, įskaitant IT paslaugų teikėjus, rinkodaros paslaugas teikiančius subjektus ir kitus. Jūs turite teisę susipažinti su savo duomenimis, juos ištaisyti ir ištrinti, jų perkelti, reikalauti apriboti tvarkymą dėl savo konkrečios situacijos, prieštarauti tvarkymui ir bet kuriuo metu atšaukti sutikimą. Sutikimo atšaukimas neturi įtakos iki atšaukimo atlikto apdorojimo teisėtumui. Taip pat turite teisę pateikti skundą kompetentingai priežiūros institucijai. Duomenys nebus perduodami į trečiąsias šalis ir nebus naudojami profiliavimui ar automatiniam sprendimų priėmimui. Susisiekti su administratoriumi galima el. paštu:',
    ],
    'lv' => [
        'rodo_text' => 'Jūsu personas datu pārzinis ir PTAK WARSAW EXPO sp. z o.o. ar juridisko adresi Nadarzynā (pasta indekss 05-830), Al. Katowicka 62, kas reģistrēta Valsts tiesu reģistra uzņēmēju reģistrā ar numuru KRS 0000671001, NIP 532544579. Personas dati tiks apstrādāti saskaņā ar Eiropas Parlamenta un Padomes 2016. gada 27. aprīļa Regulu (ES) 2016/679 par fizisku personu aizsardzību attiecībā uz personas datu apstrādi un šādu datu brīvu apriti un ar ko atceļ Direktīvu 95/46/EK (VDAR), pamatojoties uz minētās regulas 6. panta 1. punkta a) vai b) apakšpunktu. Dati tiks apstrādāti līdz piekrišanas atsaukšanai un periodiski pārskatīti ik pēc 2 gadiem. Jūsu personas dati var tikt nodoti trešajām personām, kas apstrādā personas datus PTAK WARSAW EXPO sp. z o.o. vārdā, pamatojoties uz datu apstrādes līgumiem. Jums ir tiesības piekļūt saviem datiem, tos labot un dzēst, saņemt datu pārnesamību, pieprasīt apstrādes ierobežošanu, iebilst pret apstrādi un jebkurā laikā atsaukt piekrišanu. Piekrišanas atsaukšana neietekmē pirms atsaukšanas veiktās apstrādes likumību. Jums ir arī tiesības iesniegt sūdzību kompetentajai uzraudzības iestādei. Dati netiks nodoti trešajām valstīm un netiks pakļauti profilēšanai vai automatizētai lēmumu pieņemšanai. Ar datu pārzini var sazināties pa e-pasta adresi:',
    ],
    'ro' => [
        'rodo_text' => 'Operatorul datelor dumneavoastră cu caracter personal este PTAK WARSAW EXPO sp. z o.o., cu sediul în Nadarzyn (cod poștal 05-830), Al. Katowicka 62, înregistrată în registrul întreprinzătorilor din Registrul Național al Judecătorilor cu numărul KRS 0000671001, NIP 532544579. Datele cu caracter personal vor fi prelucrate în conformitate cu Regulamentul (UE) 2016/679 al Parlamentului European și al Consiliului din 27 aprilie 2016 privind protecția persoanelor fizice în ceea ce privește prelucrarea datelor cu caracter personal și libera circulație a acestor date, precum și abrogarea Directivei 95/46/CE (GDPR), în temeiul articolului 6 alineatul (1) litera a) sau b) din regulamentul menționat, pentru scopurile indicate în consimțământul corespunzător. Datele vor fi prelucrate până la retragerea consimțământului și vor fi revizuite periodic la fiecare 2 ani. Datele dumneavoastră cu caracter personal pot fi transmise unor terțe părți care prelucrează date cu caracter personal în numele PTAK WARSAW EXPO sp. z o.o., în baza contractelor de prelucrare a datelor, inclusiv furnizori de servicii IT, furnizori de servicii de marketing, entități care prelucrează date în scopul recuperării creanțelor și alte entități. Aveți dreptul de acces la datele dumneavoastră, de a le rectifica și șterge, de transfer, de restricție a prelucrării în funcție de situația dumneavoastră specifică, opunere la prelucrare și retragere a consimțământului în orice moment. Retragerea consimțământului nu afectează legalitatea prelucrării anterioare retragerii. Aveți și dreptul de a depune plângere la autoritatea de supraveghere competentă. Datele nu vor fi transferate în țări terțe și nu vor fi supuse profilării sau deciziilor automate. Puteți contacta administratorul la adresa de e-mail:',
    ],
    'sk' => [
        'rodo_text' => 'Prevádzkovateľom vašich osobných údajov je spoločnosť PTAK WARSAW EXPO sp. z o.o. so sídlom v Nadarzyne (PSČ: 05-830), Al. Katowicka 62, zapísaná v registre podnikateľov Národného súdneho registra pod číslom KRS 0000671001, NIP 532544579. Osobné údaje budú spracúvané v súlade s nariadením Európskeho parlamentu a Rady (EÚ) 2016/679 z 27. apríla 2016 o ochrane fyzických osôb pri spracúvaní osobných údajov a voľnom pohybe takýchto údajov, ktoré zrušuje smernicu 95/46/ES (GDPR), na základe čl. 6 ods. 1 písm. a) alebo b) uvedeného nariadenia. Údaje budú spracúvané až do odvolania súhlasu a budú periodicky kontrolované každé 2 roky. Vaše osobné údaje môžu byť odovzdané tretím stranám, ktoré spracúvajú osobné údaje v mene spoločnosti PTAK WARSAW EXPO sp. z o.o. na základe zmlúv o spracúvaní údajov, vrátane poskytovateľov IT služieb, služieb marketingu a ďalších. Máte právo pristupovať k svojim údajom, opravovať ich, vymazávať, prenášať ich, požadovať obmedzenie spracovania z dôvodu vašej konkrétnej situácie, namietať proti spracovaniu a kedykoľvek odvolať súhlas. Odvolanie súhlasu neovplyvní zákonnosť spracovania pred týmto odvolaním. Máte tiež právo podať sťažnosť príslušnému dozornému orgánu. Vaše údaje nebudú odovzdané do tretích krajín a nebudú predmetom profilovania ani automatizovaného rozhodovania. Kontakt s administrátorom je možný na e-mailovej adrese:',
    ],
    'uk' => [
        'rodo_text' => 'Адміністратором ваших персональних даних є PTAK WARSAW EXPO sp. z o.o. із зареєстрованим офісом у Надаржині (поштовий індекс 05-830), Al. Katowicka 62, внесена до реєстру підприємців Національного судового реєстру під номером KRS 0000671001, NIP 532544579. Персональні дані обробляються відповідно до Регламенту (ЄС) 2016/679 Європейського Парламенту і Ради від 27 квітня 2016 року про захист фізичних осіб у зв’язку з обробкою персональних даних та вільним рухом таких даних, а також про скасування Директиви 95/46/ЄС (GDPR), на підставі ст. 6 ч. 1 п. a або b вказаного Регламенту для цілей, визначених у відповідних згодах. Дані обробляються до відкликання згоди і періодично переглядаються кожні 2 роки. Ваші персональні дані можуть бути передані третім особам, які обробляють персональні дані від імені PTAK WARSAW EXPO sp. z o.o. на підставі договорів про обробку даних, включаючи постачальників ІТ-послуг, постачальників маркетингових послуг та інших. Ви маєте право ознайомлюватися зі своїми даними, виправляти та видаляти їх, передавати, обмежувати обробку, заперечувати обробку та відкликати згоду в будь-який час. Відкликання попередньо наданої згоди не впливає на законність обробки до її відкликання. Ви також маєте право подати скаргу компетентному наглядовому органу. Ваші дані не будуть передані до третіх країн і не будуть оброблятися за допомогою профілювання або автоматизованого прийняття рішень. З адміністрацією можна зв’язатися за електронною поштою:',
    ],
    'fr' => [
        'rodo_text' => 'Le responsable du traitement de vos données personnelles est PTAK WARSAW EXPO sp. z o.o., situé à Nadarzyn (code postal 05-830), Al. Katowicka 62, inscrit au registre des entrepreneurs du Registre national sous le numéro KRS 0000671001, NIP 532544579. Les données personnelles seront traitées conformément au règlement (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016 relatif à la protection des personnes physiques à l’égard du traitement des données à caractère personnel et à la libre circulation de ces données, et abrogeant la directive 95/46/CE (RGPD), sur la base de l’article 6, paragraphe 1, point a) ou b) dudit règlement, aux fins indiquées dans les consentements correspondants. Les données seront traitées jusqu’au retrait du consentement et feront l’objet d’un examen périodique tous les 2 ans. Vos données personnelles peuvent être transmises à des tiers qui traitent des données pour le compte de PTAK WARSAW EXPO sp. z o.o. dans le cadre de contrats de traitement, notamment des prestataires de services informatiques, de marketing et d’autres. Vous disposez du droit d’accéder à vos données, de les corriger et supprimer, de les transférer, de demander la limitation du traitement, de vous opposer au traitement et de retirer votre consentement à tout moment. Le retrait du consentement n’affecte pas la licéité du traitement avant son retrait. Vous avez également le droit de déposer une réclamation auprès de l’autorité de contrôle compétente. Les données ne seront pas transférées vers des pays tiers et ne feront pas l’objet d’un profilage ou d’une décision automatisée. Vous pouvez contacter l’administrateur à l’adresse e-mail:',
    ],
    'es' => [
        'rodo_text' => 'El responsable del tratamiento de sus datos personales es PTAK WARSAW EXPO sp. z o.o., con sede en Nadarzyn (código postal 05-830), Al. Katowicka 62, inscrita en el registro de empresarios del Registro Nacional bajo el número KRS 0000671001, NIP 532544579. Los datos personales serán tratados de conformidad con el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos, y por el que se deroga la Directiva 95/46/CE (RGPD), sobre la base del artículo 6, apartado 1, letras a) o b), del citado Reglamento, para los fines indicados en los consentimientos correspondientes. Los datos se tratarán hasta la retirada del consentimiento y se revisarán periódicamente cada 2 años. Sus datos personales pueden ser comunicados a terceros que traten datos personales en nombre de PTAK WARSAW EXPO sp. z o.o. en virtud de contratos de tratamiento de datos, incluidos proveedores de servicios informáticos, servicios de marketing y otros. Tiene derecho a acceder a sus datos, corregirlos y eliminarlos, transferirlos, solicitar la limitación del tratamiento por motivos específicos, oponerse al tratamiento y retirar su consentimiento en cualquier momento. La retirada previa del consentimiento no afecta a la licitud del tratamiento realizado antes de la retirada. También tiene derecho a presentar una reclamación ante la autoridad de control competente. Sus datos no serán transferidos a terceros países ni se someterán a perfiles ni decisiones automatizadas. Puede contactar con el responsable a través del correo electrónico:',
    ],
];
